apiVersion: v1
kind: Pod
metadata:
  name: web-color-red
  labels:
    app: web-color
spec:
  containers:
  - name: simple-webapp-color
    image: mmumshad/simple-webapp-color:local
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
