apiVersion: v1
kind: Service
metadata:
  name: app-color-service
spec:
  type: NodePort
  selector:
    app: web-color
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
